services:
  # Backend Node.js Application
  notification-service:
    image: ghcr.io/tambongstercy/antic-notifications-backend:v1.0.0
    container_name: antic-notification-service
    ports:
      - "3000:3000"
      - "3002:3002"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      WEBSOCKET_PORT: 3002
      MONGODB_URI: mongodb://172.17.0.1:27017/notification-service
      WHATSAPP_SESSION_PATH: /app/sessions/whatsapp
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - notification-network
    # Network improvements for WhatsApp connectivity
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_keepalive_time=600
      - net.ipv4.tcp_keepalive_intvl=60
      - net.ipv4.tcp_keepalive_probes=3
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    # Add specific hosts for WhatsApp connectivity
    extra_hosts:
      - "web.whatsapp.com:157.240.22.53"
      - "www.whatsapp.com:157.240.22.53"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits to prevent overwhelming
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Frontend React Application
  admin-dashboard:
    image: ghcr.io/tambongstercy/antic-notifications-admin:v1.0.2
    container_name: antic-admin-dashboard
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - notification-network
    depends_on:
      notification-service:
        condition: service_healthy

networks:
  notification-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-antic-notif
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1